### ISSUE TITLE
LICENSE, or lack thereof

### ISSUE THREAD

**Issue by samueldr** [thefloweringash/kevin-nix#3]
Hi!

I would like to correctly source the license and attribution information for depthcharge shenanigans in mobile-nixos (WIP). Though, the only thing I'm using is `modules/make-kernel-its.sh`, it is a well written script and don't really need nor intend to re-implement it.

Can you add licensing information, and what attribution I should use?

Thanks!

**Comment by thefloweringash** [comment]
I've added a LICENSE file for things original to this repository. I think that resolves the issue, if not please reopen.

**Comment by samueldr** [comment]
Thanks!
