### ISSUE TITLE
error: attribute 'lib' missing

### ISSUE THREAD

**Issue by rambler41** [thefloweringash/kevin-nix#5]
I have been unable to find a suitable solution to this error.  My desktop version is 23.05 and I have verified the packages.  Could you offer some advice?
Thanks

[dad@nixos:~/Projects/kevin-nix-master]$  nix-build release.nix -A sdImage
error: attribute 'lib' missing

       at /home/dad/Projects/kevin-nix-master/packages/linux_gru_4_4/default.nix:29:1:

           28|
           29| stdenv.lib.extendDerivation true passthru drv
             | ^
           30|
(use '--show-trace' to show detailed location information)

[dad@nixos:~/Projects/kevin-nix-master]$

**Comment by samueldr** [comment]
This project hasn't been updated since a while, and `stdenv` stopped providing a (convenient?) copy of `lib` since.

You should be able to replace all `stdenv.lib` with `lib` *if* you ensure it's also added to the inputs of the callPackage.

**Comment by rambler41** [comment]
That resolved my issue, closing issue.  Thanks
